// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Utility.ORM_UT.TestCase
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class RelationObjectOperatorFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RelationObjectOperator.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "RelationObjectOperator", "提供關連資料物件操作。", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "RelationObjectOperator")))
            {
                Utility.ORM_UT.TestCase.RelationObjectOperatorFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("取得指定的關連資料物件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RelationObjectOperator")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RelationObjectOperator")]
        public virtual void 取得指定的關連資料物件()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("取得指定的關連資料物件", new string[] {
                        "RelationObjectOperator"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name"});
            table1.AddRow(new string[] {
                        "3752",
                        "TOHU"});
#line 6
 testRunner.Given("資料表 Custom 資料表符合條件的記錄", ((string)(null)), table1, "Given ");
#line 9
 testRunner.When("要求取得欄位 ID 為 3752 的 CustomObject 關連資料物件", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name"});
            table2.AddRow(new string[] {
                        "3752",
                        "TOHU"});
#line 10
 testRunner.Then("取得 CustomObject 資料物件", ((string)(null)), table2, "Then ");
#line 13
  testRunner.And("得到執行語法 SELECT * FROM Custom WHERE [ID] = @ID_1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table3.AddRow(new string[] {
                        "@ID_1",
                        "3752"});
#line 14
  testRunner.And("得到查詢參數集合包含", ((string)(null)), table3, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("新增指定的關連資料物件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RelationObjectOperator")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RelationObjectOperator")]
        public virtual void 新增指定的關連資料物件()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("新增指定的關連資料物件", new string[] {
                        "RelationObjectOperator"});
#line 19
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name"});
            table4.AddRow(new string[] {
                        "3752",
                        "TOHU"});
            table4.AddRow(new string[] {
                        "0001",
                        "ALL"});
#line 20
 testRunner.Given("關連資料物件集合", ((string)(null)), table4, "Given ");
#line 24
 testRunner.When("要求新增關連資料物件", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
 testRunner.Then("得到執行語法 INSERT INTO [Custom] ( [ID], [Name] ) VALUES ( @ID, @Name )", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table5.AddRow(new string[] {
                        "@ID",
                        "3752"});
            table5.AddRow(new string[] {
                        "@Name",
                        "TOHU"});
#line 26
  testRunner.And("得到參數集合包含", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table6.AddRow(new string[] {
                        "@ID",
                        "0001"});
            table6.AddRow(new string[] {
                        "@Name",
                        "ALL"});
#line 30
  testRunner.And("得到參數集合包含", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("刪除指定的關連資料物件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RelationObjectOperator")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RelationObjectOperator")]
        public virtual void 刪除指定的關連資料物件()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("刪除指定的關連資料物件", new string[] {
                        "RelationObjectOperator"});
#line 36
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name"});
            table7.AddRow(new string[] {
                        "3752",
                        "TOHU"});
            table7.AddRow(new string[] {
                        "0001",
                        "ALL"});
#line 37
 testRunner.Given("關連資料物件集合", ((string)(null)), table7, "Given ");
#line 41
  testRunner.And("條件為欄位 ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.When("要求刪除關連資料物件", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.Then("得到執行語法 DELETE FROM [Custom] WHERE [ID] = @ID_1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table8.AddRow(new string[] {
                        "@ID_1",
                        "3752"});
#line 44
  testRunner.And("得到參數集合包含", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table9.AddRow(new string[] {
                        "@ID_1",
                        "0001"});
#line 47
  testRunner.And("得到參數集合包含", ((string)(null)), table9, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("更新指定的關連資料物件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RelationObjectOperator")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RelationObjectOperator")]
        public virtual void 更新指定的關連資料物件()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("更新指定的關連資料物件", new string[] {
                        "RelationObjectOperator"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name"});
            table10.AddRow(new string[] {
                        "3752",
                        "TOHU"});
            table10.AddRow(new string[] {
                        "0001",
                        "ALL"});
#line 53
 testRunner.Given("關連資料物件集合", ((string)(null)), table10, "Given ");
#line 57
  testRunner.And("條件為欄位 ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
  testRunner.And("更新欄位 Name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.When("要求更新關連資料物件", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
 testRunner.Then("得到執行語法 UPDATE [Custom] SET ( [Name] = @Name_1 ) WHERE [ID] = @ID_1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table11.AddRow(new string[] {
                        "@ID_1",
                        "3752"});
            table11.AddRow(new string[] {
                        "@Name_1",
                        "TOHU"});
#line 61
  testRunner.And("得到參數集合包含", ((string)(null)), table11, "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table12.AddRow(new string[] {
                        "@ID_1",
                        "0001"});
            table12.AddRow(new string[] {
                        "@Name_1",
                        "ALL"});
#line 65
  testRunner.And("得到參數集合包含", ((string)(null)), table12, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("無條件式更新指定的關連資料物件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RelationObjectOperator")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RelationObjectOperator")]
        public virtual void 無條件式更新指定的關連資料物件()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("無條件式更新指定的關連資料物件", new string[] {
                        "RelationObjectOperator"});
#line 71
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name"});
            table13.AddRow(new string[] {
                        "3752",
                        "TOHU"});
            table13.AddRow(new string[] {
                        "0001",
                        "ALL"});
#line 72
 testRunner.Given("關連資料物件集合", ((string)(null)), table13, "Given ");
#line 76
  testRunner.And("更新欄位 Name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.When("要求更新關連資料物件", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
 testRunner.Then("得到執行語法 UPDATE [Custom] SET ( [Name] = @Name_1 )", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table14.AddRow(new string[] {
                        "@Name_1",
                        "TOHU"});
#line 79
  testRunner.And("得到參數集合包含", ((string)(null)), table14, "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Key",
                        "Value"});
            table15.AddRow(new string[] {
                        "@Name_1",
                        "ALL"});
#line 82
  testRunner.And("得到參數集合包含", ((string)(null)), table15, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("無條件式取得指定的關連資料物件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RelationObjectOperator")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RelationObjectOperator")]
        public virtual void 無條件式取得指定的關連資料物件()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("無條件式取得指定的關連資料物件", new string[] {
                        "RelationObjectOperator"});
#line 87
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name"});
            table16.AddRow(new string[] {
                        "3752",
                        "TOHU"});
#line 88
 testRunner.Given("資料表 Custom 資料表符合條件的記錄", ((string)(null)), table16, "Given ");
#line 91
 testRunner.When("要求取得 Custom 關連資料物件", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name"});
            table17.AddRow(new string[] {
                        "3752",
                        "TOHU"});
#line 92
 testRunner.Then("取得 CustomObject 資料物件", ((string)(null)), table17, "Then ");
#line 95
  testRunner.And("得到執行語法 SELECT * FROM Custom", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("無條件刪除指定的關連資料物件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RelationObjectOperator")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("RelationObjectOperator")]
        public virtual void 無條件刪除指定的關連資料物件()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("無條件刪除指定的關連資料物件", new string[] {
                        "RelationObjectOperator"});
#line 98
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "ID",
                        "Name"});
            table18.AddRow(new string[] {
                        "3752",
                        "TOHU"});
            table18.AddRow(new string[] {
                        "0001",
                        "ALL"});
#line 99
 testRunner.Given("關連資料物件集合", ((string)(null)), table18, "Given ");
#line 103
 testRunner.When("要求刪除關連資料物件", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 104
 testRunner.Then("得到執行語法 DELETE FROM [Custom]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
